version: '3.5'

services:
  mosquitto:
    container_name: nebula_mosquitto_container
    image: eclipse-mosquitto:2.0.14
    volumes:
      - ./config:/mosquitto/config/
      - ./log/mqtt:/mqtt/log
    ports:
      - '1883:1883'
      - '8883:8883'
    networks:
      - default
    restart: unless-stopped

networks:
  default:
